-- Revoke default public execute permissions
REVOKE EXECUTE ON FUNCTION public.get_profit_summary(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_profit_summary(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) FROM anon;
GRANT EXECUTE ON FUNCTION public.get_profit_summary(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_profit_summary(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) TO service_role;

REVOKE EXECUTE ON FUNCTION public.get_profit_timeseries(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_profit_timeseries(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) FROM anon;
GRANT EXECUTE ON FUNCTION public.get_profit_timeseries(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_profit_timeseries(TIMESTAMP WITH TIME ZONE, TIMESTAMP WITH TIME ZONE) TO service_role;

REVOKE EXECUTE ON FUNCTION public.get_shop_owner_stats() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_shop_owner_stats() FROM anon;
GRANT EXECUTE ON FUNCTION public.get_shop_owner_stats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_shop_owner_stats() TO service_role;

REVOKE EXECUTE ON FUNCTION public.get_wallet_overview() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_wallet_overview() FROM anon;
GRANT EXECUTE ON FUNCTION public.get_wallet_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_wallet_overview() TO service_role;
