'use client'

import {
    Smartphone,
    Home,
    Shirt,
    Sparkles,
    Wrench,
    Hammer,
    Trophy,
    Baby,
    Car,
    Laptop,
    Tv,
    Gamepad2,
    Music,
    Headphones,
    Camera,
    Video,
    Wifi,
    Printer,
    Monitor,
    Armchair,
    Lightbulb,
    Box,
    Microwave,
    UtensilsCrossed,
    Droplet,
    Droplets,
    Leaf,
    Scissors,
    Smile,
    Flower,
    Palette,
    Pill,
    Zap,
    Blocks,
    Bolt,
    DoorOpen,
    Bed,
    Footprints,
    Backpack,
    Heart,
    BookOpen,
    Hand,
    Tent,
    Cigarette,
    Film,
    Dumbbell,
    Settings,
    Bike,
    Bus,
    Truck,
    Anchor,
    Flame,
    Wind,
    Shield,
    Factory,
    ShoppingBag,
} from 'lucide-react'

// Maps the icon-name strings stored in classified_categories.icon (see the
// migration RUN_ON_PRODUCTION_marketplace_bundle.sql, section 15) to lucide
// components. Every name here MUST be a real lucide-react export.
const iconMap: Record<string, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
    Smartphone,
    Home,
    Shirt,
    Sparkles,
    Wrench,
    Hammer,
    Trophy,
    Baby,
    Car,
    Laptop,
    Tv,
    Gamepad2,
    Music,
    Headphones,
    Camera,
    Video,
    Wifi,
    Printer,
    Monitor,
    Armchair,
    Lightbulb,
    Box,
    Microwave,
    UtensilsCrossed,
    Droplet,
    Droplets,
    Leaf,
    Scissors,
    Smile,
    Flower,
    Palette,
    Pill,
    Zap,
    Blocks,
    Bolt,
    DoorOpen,
    Bed,
    Footprints,
    Backpack,
    Heart,
    BookOpen,
    Hand,
    Tent,
    Cigarette,
    Film,
    Dumbbell,
    Settings,
    Bike,
    Bus,
    Truck,
    Anchor,
    Flame,
    Wind,
    Shield,
    Factory,
}

interface CategoryIconProps {
    name?: string | null
    className?: string
    style?: React.CSSProperties
}

export function CategoryIcon({ name, className = 'w-6 h-6', style }: CategoryIconProps) {
    const Icon = name && iconMap[name] ? iconMap[name] : ShoppingBag
    return <Icon className={className} style={style} />
}
