'use client'

import {
    Smartphone,
    Home,
    Shirt,
    Sparkles,
    Wrench,
    Hammer,
    Trophy,
    Baby,
    Car,
    Laptop,
    Tv,
    Gamepad2,
    Music,
    Headphones,
    Camera,
    VideoIcon,
    Wifi,
    Printer,
    Monitor,
    Chair,
    Lightbulb,
    BoxIcon,
    Microwave,
    UtensilsCrossed,
    Droplet,
    Leaf,
    Dress,
    Scissors,
    Droplets,
    Flower,
    Palette,
    Pill,
    Zap,
    Brick,
    Bolt,
    DoorOpen,
    Bed,
    Footprints,
    Backpack,
    Stroller,
    Heart,
    BookOpen,
    Hand,
    Tent,
    Cigarette,
    Film,
    Dumbbell,
    Settings,
    Bike,
    Bus,
    Truck,
    Anchor,
    Monitor as MonitorIcon,
    Flame,
    Wind,
    Shield,
    Factory,
    ShoppingBag,
    Smile,
} from 'lucide-react'

type IconName = string

const iconMap: Record<IconName, React.ComponentType<{ className?: string; style?: React.CSSProperties }>> = {
    Smartphone,
    Home,
    Shirt,
    Sparkles,
    Wrench,
    Hammer,
    Trophy,
    Baby,
    Car,
    Laptop,
    Tv,
    Gamepad2,
    Music,
    Headphones,
    Camera,
    VideoIcon,
    Wifi,
    Printer,
    Monitor,
    Chair,
    Lightbulb,
    BoxIcon,
    Microwave,
    UtensilsCrossed,
    Droplet,
    Leaf,
    Dress,
    Scissors,
    Droplets,
    Flower,
    Palette,
    Pill,
    Zap,
    Brick,
    Bolt,
    DoorOpen,
    Bed,
    Footprints,
    Backpack,
    Stroller,
    Heart,
    BookOpen,
    Hand,
    Tent,
    Cigarette,
    Film,
    Dumbbell,
    Settings,
    Bike,
    Bus,
    Truck,
    Anchor,
    Flame,
    Wind,
    Shield,
    Factory,
    Smile,
}

interface CategoryIconProps {
    name?: string | null
    className?: string
    style?: React.CSSProperties
}

export function CategoryIcon({ name, className = 'w-6 h-6', style }: CategoryIconProps) {
    const Icon = name && iconMap[name] ? iconMap[name] : ShoppingBag

    return <Icon className={className} style={style} />
}
